# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SetSize <- function(size) {
    invisible(.Call('_TakuzuMickaelLoikPackage_SetSize', PACKAGE = 'TakuzuMickaelLoikPackage', size))
}

GetSize <- function() {
    .Call('_TakuzuMickaelLoikPackage_GetSize', PACKAGE = 'TakuzuMickaelLoikPackage')
}

mainGenerate <- function() {
    invisible(.Call('_TakuzuMickaelLoikPackage_mainGenerate', PACKAGE = 'TakuzuMickaelLoikPackage'))
}

GetCaseValue <- function(i, j) {
    .Call('_TakuzuMickaelLoikPackage_GetCaseValue', PACKAGE = 'TakuzuMickaelLoikPackage', i, j)
}

GetHiddenCaseValue <- function(i, j) {
    .Call('_TakuzuMickaelLoikPackage_GetHiddenCaseValue', PACKAGE = 'TakuzuMickaelLoikPackage', i, j)
}

PlayerChangeValue <- function(i, j) {
    invisible(.Call('_TakuzuMickaelLoikPackage_PlayerChangeValue', PACKAGE = 'TakuzuMickaelLoikPackage', i, j))
}

CheckVictory <- function() {
    .Call('_TakuzuMickaelLoikPackage_CheckVictory', PACKAGE = 'TakuzuMickaelLoikPackage')
}

GetErrorCells <- function() {
    .Call('_TakuzuMickaelLoikPackage_GetErrorCells', PACKAGE = 'TakuzuMickaelLoikPackage')
}

HelpPlayer <- function(iteration) {
    invisible(.Call('_TakuzuMickaelLoikPackage_HelpPlayer', PACKAGE = 'TakuzuMickaelLoikPackage', iteration))
}

